apiVersion: v1
kind: Service
metadata:
  name: rafiq-print-store-service
spec:
  selector:
    app: rafiq-print-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
