name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - main  # শুধুমাত্র main ব্রাঞ্চে পুশ হলে ওয়ার্কফ্লো ট্রিগার হবে

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu ভার্চুয়াল মেশিন ব্যবহার করুন

    steps:
      # 1. রিপোজিটরি চেক আউট করুন
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Java সেট আপ করুন
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Maven ব্যবহার করে প্রজেক্ট বিল্ড করুন
      - name: Build with Maven
        run: mvn clean package

      # 4. JAR ফাইল আপলোড করুন (যদি প্রয়োজন হয়)
      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: target/Rafiq-print-store.jar  # আপনার JAR ফাইলের পাথ

  deploy:
    runs-on: ubuntu-latest
    needs: build  # build জব সম্পূর্ণ হওয়ার পর deploy জব শুরু হবে

    steps:
      # 1. রিপোজিটরি চেক আউট করুন
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Java সেট আপ করুন
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. বিল্ড করা JAR ফাইল ডাউনলোড করুন
      - name: Download JAR file
        uses: actions/download-artifact@v3
        with:
          name: spring-boot-app
          path: target/

      # 4. JAR ফাইল রান করুন (যদি লোকাল টেস্টিং এর জন্য প্রয়োজন হয়)
      - name: Run Spring Boot App
        run: java -jar target/Rafiq-print-store.jar